# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

name: '$(version).$(Rev:r)'

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: WhiteSource Bolt@20
  inputs:
    advance: true

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'twolittlebirds'
    scannerMode: 'MSBuild'
    projectKey: 'TwoLittleBirds_liminal-webapi'
    projectName: 'liminal-webapi'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      #sonar.exclusions=**/*.bin

- task: DotNetCoreCLI@2
  displayName: 'DotNet Test'
  inputs:
    command: 'test'
    projects: 'liminal-webapi_tests/liminal-webapi_tests.csproj'
    testRunTitle: 'liminal-webapi unit tests'

- task: DotNetCoreCLI@2
  displayName: 'DotNet Publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'liminal-webapi/liminal-webapi.csproj'
    arguments: '--configuration $(BuildConfiguration) /p:Version=$(Build.BuildNumber) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'


