# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

name: $(Build.BuildId)

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'twolittlebirds/liminal'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/dockerfile.prod'